name: Update Docker image if base google image is updated. 

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Check base image has updated beyond our image
        id: check
        uses: twiddler/is-my-docker-parent-image-out-of-date@v1
        with:
          parent-image: "gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine"
          my-image: "docker.io/complacentsee/googlednsupdate"

      - name: Build Docker Image
        if: steps.check.outputs.out-of-date == 'true'
        uses: ./.github/actions/buildandpushdockerimage

